version: '3.9'

services:

  db_redis:
    container_name: db_redis
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always

  db_mongo:
    container_name: db_mongo
    image: mongo:${MONGO_VERSION}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - mongo
    volumes:
      - ./mongodb/mongod.conf:/etc/mongod.conf:r
      - ./mongodb/data:/data/db:rw
      - ./mongodb/logs:/var/log/mongodb:rw
    command: ["-f", "/etc/mongod.conf"]
    env_file:
      - .env
    restart: always

  db_mongo_express:
    depends_on:
      - db_mongo
      # heaviest service, so it starts last
      - api_go_fiber
    container_name: db_mongo_express
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    networks:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=db_mongo
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    restart: always

  db_mysql:
    container_name: db_mysql
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - mysql
    volumes:
      #- ./mysql.conf:/etc/mysql/conf.d:r
      #! use later: - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh:r
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE_ACCOUNTS=${MYSQL_DATABASE_ACCOUNTS}
      #- MYSQL_ALLOW_EMPTY_PASSWORD=true
      #- MYSQL_ROOT_HOST=localhost
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  db_phpmyadmin:
    depends_on:
      - db_mysql
    container_name: db_phpmyadmin
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - mysql
    environment:
      - PMA_HOST=db_mysql
      - PMA_PORT=${MYSQL_PORT}
      - PMA_USER=${PHPMYADMIN_USER}
      - PMA_PASSWORD=${PHPMYADMIN_PASSWORD}
    restart: always

  api_go_fiber:
    #depends_on:
      #- db_mongo
      #- db_redis
    container_name: api_go_fiber
    build: ./go_fiber
    #environment:
      #- MONGODB_CONNECTION_STRING=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@db_mongo:${MONGO_PORT}
      #- REDIS_CONNECTION_STRING=db_redis:${REDIS_PORT}
    ports:
      - ${GO_FIBER_PORT}:3000
    #networks:
      #- mongo
      #- redis
      #- mysql
    restart: always

  app_svelte_loldraft:
    container_name: app_svelte_loldraft
    build: ./app_svelte_loldraft
    ports:
      - ${LOLDRAFT_PORT}:3000
    restart: always

networks:
  mongo:
    driver: bridge
  redis:
    driver: bridge
  mysql:
    driver: bridge